id: 131073
command: 'configure'
args : '{ "urdf": { "name": "right_gripper_mass",  "link": [ { "name": "right_gripper_mass", "inertial": { "mass": { "value": 1.0 }, "origin": { "xyz": [-0.02, 0.0, 0.05] } } } ] } }'
